import type { Testimonial } from "@/types"

// Real 5-star reviews transcribed from the clinic's Google Business Profile.
// Snapshot as of Jul 2026 — not live-synced.
export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Tanmay Saxena",
    initials: "TS",
    rating: 5,
    text: "Dr. Jatin Gupta provided me with the Invisible Aligners treatment that lasted for 8 months and I am extremely happy and satisfied with the results. The gaps inbetween my teeth are now next to nothing and I feel I made a really good decision…",
    treatment: "Invisible Aligners",
    date: "a week ago",
    reviewCount: "7 reviews · 3 photos",
    color: "from-emerald-500 to-teal-600",
  },
  {
    id: "2",
    name: "U K Goel",
    initials: "UK",
    rating: 5,
    text: "Dr. Jatin Gupta and Dr. Shefli Gupta of Shine Dental clinic are highly skilled, professional, and attentive in explaining treatments related to dental like root canal, implants and others. My treatment of tooth implantation done by Dr Jatin went very smooth, peaceful efficient and meticulous with minimum pain. Commendable. The clinic's staff is cooperative and caring, the environment is clean and hygienic, and equipped with all modern machines and facilities as per norms. I left fully satisfied and feel safe under his treatment.",
    treatment: "Dental Implants",
    date: "7 months ago",
    reviewCount: "7 reviews",
    color: "from-indigo-500 to-blue-600",
  },
  {
    id: "3",
    name: "Komal Machal",
    initials: "K",
    rating: 5,
    text: "My experience was absolutely wonderful. Dr. Jatin gupta ji is an excellent dentist, and I got my teeth treated. I had a cavity, which they fixed very well. The doctor's demeanor was very kind and humble, which was very satisfying for me. I felt much better after the treatment. The doctor's staff was also very supportive and nice. The clinic maintains very good cleanliness. I highly and sincerely recommend them. Thank You Very Much sir!",
    treatment: "Cavity Filling",
    date: "5 months ago",
    reviewCount: "1 review",
    color: "from-green-500 to-emerald-600",
  },
  {
    id: "4",
    name: "Tuba Hashmi",
    initials: "TH",
    rating: 5,
    text: "Got my wisdom tooth extracted and it was a good experience i must say. Minimal pain, good follow up treatment and high quality x ray available. Clinic is very hygienic and everyone including dr is very helpful and humble.. wil look forward in future too.",
    treatment: "Wisdom Tooth Extraction",
    date: "5 months ago",
    reviewCount: "4 reviews",
    color: "from-amber-500 to-orange-600",
  },
  {
    id: "5",
    name: "Rajveer Kaur",
    initials: "R",
    rating: 5,
    text: "I have visited Shine Dental and Medical Clinic for my dental treatment and I am highly satisfied with the professionalism of Dr. Jatin Gupta. They explained everything from the first step to the final stage, making my treatment as smooth as possible.",
    treatment: "General Dental Care",
    date: "4 months ago",
    reviewCount: "1 review",
    color: "from-rose-500 to-pink-600",
  },
  {
    id: "6",
    name: "Poonam Jain",
    initials: "P",
    rating: 5,
    text: "I have taken treatment from Dr. Jatin Gupta ji and I found his nature and treatment both very good and the nature of the staff was also very good.",
    treatment: "General Dental Care",
    date: "a month ago",
    reviewCount: "1 review",
    color: "from-sky-500 to-blue-600",
  },
  {
    id: "7",
    name: "Sumit Kumar",
    initials: "SK",
    rating: 5,
    text: "Dr. Jatin has handled my case very well, explaining everything clearly despite the many complications involved. I was very scared, but I'm satisfied with the treatment he provided. Dr. Jatin is a good Dental Surgeon... Outstanding professionalism and friendliness. Every visit feels like visiting a friend. Dr. Jatin Gupta is an amazing doctor. Thank you for all being so kind and making this a great experience.",
    treatment: "General Dental Care",
    date: "8 months ago",
    reviewCount: "1 review",
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "8",
    name: "Praveen Kumar",
    initials: "PK",
    rating: 5,
    text: "Shine dental clinic. Dr Jatin is ultimate, co-treatment with Dr Abhinav Singh (visiting Orthodontist) is also perfect.",
    treatment: "Orthodontic Care",
    date: "5 months ago",
    reviewCount: "8 reviews · 2 photos",
    color: "from-cyan-500 to-teal-600",
  },
  {
    id: "9",
    name: "Seema Tomar",
    initials: "ST",
    rating: 5,
    text: "I've been going to Dr jatin gupta for a while now, and I couldn't be happier with the care I receive. The whole team is professional, kind, and always makes me feel comfortable. They take the time to explain everything clearly and genuinely care about their patients. Highly recommend to anyone looking for a skilled and trustworthy dentist!",
    treatment: "General Dental Care",
    date: "a year ago",
    reviewCount: "2 reviews",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "10",
    name: "Mohd Danish",
    initials: "MD",
    rating: 5,
    text: "Mere teeth mai kafi jada pain tha to maine Dr. se suggestion liya but sabhi dr. ne teeth ko nikalne ke liye bola but maine google pr search kiya to Dr. Jatin Gupta ka naam samne aaya or maine unhe dikhaya to unhone mere painless treatment kiya or mere teeth nikalne se bach gya or ab mera teeth bilkul thik h.",
    treatment: "Root Canal Treatment",
    date: "8 months ago",
    reviewCount: "3 reviews",
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "11",
    name: "Amit Kannojiya",
    initials: "AK",
    rating: 5,
    text: "Absolutely the best dental experience! The clinic is so neat and clean and follows top hygiene standards. I was very scared for the dental treatment but doctor made me relaxed by answering my all the questions and after that I could get my one root canal treatment and 3 implants done comfortably. I highly recommend this clinic.",
    treatment: "Root Canal & Implants",
    date: "11 months ago",
    reviewCount: "1 review",
    color: "from-blue-500 to-indigo-600",
  },
]
